// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzfB1GR-0GSCGA4Rm_2wkfSuQNJwkp9b4',
    appId: '1:465716006110:web:95e128b0d136d237aa464f',
    messagingSenderId: '465716006110',
    projectId: 'tennis-motskin',
    authDomain: 'tennis-motskin.firebaseapp.com',
    storageBucket: 'tennis-motskin.firebasestorage.app',
    measurementId: 'G-3WDH79X5W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbuigSXRZO3tE_l-B6q7KyKjqGMyol7cU',
    appId: '1:465716006110:android:b32e5901687d3fdbaa464f',
    messagingSenderId: '465716006110',
    projectId: 'tennis-motskin',
    storageBucket: 'tennis-motskin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiJNh8nt5Wd5Q_2Rnf49kExdCXsbc7eug',
    appId: '1:465716006110:ios:4065bc8b0509c36baa464f',
    messagingSenderId: '465716006110',
    projectId: 'tennis-motskin',
    storageBucket: 'tennis-motskin.firebasestorage.app',
    iosBundleId: 'com.example.tennismotskin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiJNh8nt5Wd5Q_2Rnf49kExdCXsbc7eug',
    appId: '1:465716006110:ios:4065bc8b0509c36baa464f',
    messagingSenderId: '465716006110',
    projectId: 'tennis-motskin',
    storageBucket: 'tennis-motskin.firebasestorage.app',
    iosBundleId: 'com.example.tennismotskin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzfB1GR-0GSCGA4Rm_2wkfSuQNJwkp9b4',
    appId: '1:465716006110:web:9152ab50c9801647aa464f',
    messagingSenderId: '465716006110',
    projectId: 'tennis-motskin',
    authDomain: 'tennis-motskin.firebaseapp.com',
    storageBucket: 'tennis-motskin.firebasestorage.app',
    measurementId: 'G-QTYPBQCX55',
  );
}
